bump pyo3 from 0.25.1 to 0.29.0 (#1320)
### Changelog
None

### Docs
None

### Description
This change updates pyo3 to the latest version, to address a security
vulnerability. The changes are fairly mechanical:

- `py.allow_threads` -> `py.detach`
- `Python::with_gil` -> `Python::attach`
- `PyObject` -> `Py<PyAny>`
- `Bound::downcast` -> `Bound::cast`
- Explicit `from_py_object` derive for types that impl Clone

See the migration guide for reference:
https://pyo3.rs/v0.29.0/migration.html

TypeError messages for argument conversions have also changed slightly
to look more native. The old exceptions had a message like this:

```
TypeError: argument 'metadata': 'int' object cannot be converted to 'PyString'
```

New ones include a "while processing '<field name>'" as a PEP 678 note:

```
TypeError: 'int' object is not an instance of 'str'
while processing 'metadata'
```

Fixes: https://github.com/foxglove/foxglove-sdk/security/dependabot/180